### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dimpolo** [Ardelean-Calin/ltr303-rs#3]
Hey, thanks again for you work!
If it's not rude to ask, could we maybe change the license to a more permissive one?
Most crates in the Rust ecosystem seem to be dual-licensed under the Apache License, Version 2.0 and the MIT license.
If this doesn't sit well with you, I would of course understand!

**Comment by acalinp** [comment]
Hi! Thanks for the suggestion. I have updated the license to Apache Version 2.0, I'm no legal expert but I felt MIT was a bit too permissive, so after some quick reading up, I chose to use Apache. I hope this is fine with your use-case as well :)

**Comment by dimpolo** [comment]
That's perfect. Thank you very much!
